import sqlite3
import pandas as pd

# Project metadata and header configuration
MARKDOWN_HEADER = (
    "# Twitch Advanced SQLite Analysis\n\n"
    "**Dataset Timeline:** Metrics captured across the 2023 - 2024 streaming calendar.\n\n"
    "This portfolio project leverages Python, Pandas, and SQLite to run data pipelines "
    "and extract meaningful business insights from streaming data tracking the Top 1000 Twitch Streamers.\n\n"
)

# Structured analytical queries with built-in documentation
QUERIES = {
    "Top 5 Most Streamed Games Overall": {
        "sql": """
            SELECT most_streamed_game, COUNT(*) as streamer_count
            FROM streamers
            GROUP BY most_streamed_game
            ORDER BY streamer_count DESC
            LIMIT 5;
        """,
        "desc": "Generated by grouping the dataset by game titles and counting unique broadcaster entries. This identifies market saturation and directory popularity, showing where the highest density of creator competition exists."
    },
    
    "Average Followers by Language (Languages with >10 Streamers)": {
        "sql": """
            SELECT language, CAST(AVG(total_followers) AS INT) as avg_followers, COUNT(*) as total_streamers
            FROM streamers
            GROUP BY language
            HAVING total_streamers > 10
            ORDER BY avg_followers DESC
            LIMIT 5;
        """,
        "desc": "Calculated by averaging total subscriber counts across distinct language demographics. Broadcasters are filtered out if their language group has fewer than 11 representatives to eliminate skewing from statistical anomalies."
    },
    
    "Stream Duration Tiers vs. Average Followers Gained": {
        "sql": """
            SELECT 
                CASE 
                    WHEN average_stream_duration < 4 THEN 'Short (Under 4 hrs)'
                    WHEN average_stream_duration BETWEEN 4 AND 8 THEN 'Medium (4 to 8 hrs)'
                    ELSE 'Long (Over 8 hrs)'
                END as stream_length,
                CAST(AVG(followers_gained_per_stream) AS INT) as avg_followers_gained
            FROM streamers
            GROUP BY stream_length
            ORDER BY avg_followers_gained DESC;
        """,
        "desc": "Uses a conditional CASE statement to bin broadcast sessions into duration tiers. By aggregating the average follower gain per stream against these groups, the data exposes the relationship between broadcast length and viewer conversion efficiency."
    },
    
    "Top Games for Individual Streamer Follower Growth": {
        "sql": """
            SELECT most_streamed_game, CAST(AVG(followers_gained_per_stream) AS INT) AS avg_followers_gained
            FROM streamers
            GROUP BY most_streamed_game
            ORDER BY avg_followers_gained DESC
            LIMIT 5;
        """,
        "desc": "Isolates individual channel velocity by measuring the average follower acquisition rate per live session. This highlights which specific gaming categories yield the highest return on investment for new creator exposure."
    },
    
    "Streamer Growth Efficiency Profile (Followers Generated per Hour)": {
        "sql": """
            WITH StreamerEfficiency AS (
                SELECT name, most_streamed_game, total_time_streamed, total_followers,
                (total_followers * 1.0 / total_time_streamed) AS followers_per_hour_streamed
                FROM streamers
                WHERE total_time_streamed > 1000 
            )
            SELECT name, most_streamed_game, ROUND(followers_per_hour_streamed, 2) AS efficiency_score
            FROM StreamerEfficiency
            ORDER BY efficiency_score DESC
            LIMIT 5;
        """,
        "desc": "Utilizes a Common Table Expression (CTE) to establish a baseline performance KPI: follower acquisition scaled against total broadcast volume. Channels with fewer than 1,000 streamed hours are omitted to spotlight highly optimized, long-term talent profiles."
    },
    
    "Most Optimized Day of the Week to Stream per Game": {
        "sql": """
            WITH GameDayStats AS (
                SELECT most_streamed_game, day_with_most_followers_gained AS best_day,
                AVG(followers_gained_per_stream) AS avg_growth
                FROM streamers
                GROUP BY most_streamed_game, day_with_most_followers_gained
            ),
            RankedDays AS (
                SELECT most_streamed_game, best_day, CAST(avg_growth AS INT) AS avg_growth,
                ROW_NUMBER() OVER(PARTITION BY most_streamed_game ORDER BY avg_growth DESC) as rank
                FROM GameDayStats
            )
            SELECT most_streamed_game, best_day, avg_growth
            FROM RankedDays
            WHERE rank = 1
            ORDER BY avg_growth DESC
            LIMIT 5;
        """ ,
        "desc": "Leverages a window function (`ROW_NUMBER() OVER`) to partition aggregate viewer metrics by category title. The logic computes growth performance per day, ranks them independently within each game marketplace, and returns only the single most profitable broadcast day."
    }
}

markdown_output = MARKDOWN_HEADER

# Process database records and build out document components
with sqlite3.connect('twitch.db') as conn:
    for i, (title, content) in enumerate(QUERIES.items(), 1):
        df = pd.read_sql_query(content["sql"], conn)
        
        print(f"\n--- {title.upper()} ---")
        print(df)
        
        # Structure the section blocks sequentially
        markdown_output += f"### {i}. {title}\n"
        markdown_output += f"*{content['desc']}*\n\n"
        markdown_output += df.to_markdown(index=False) + "\n\n"
        markdown_output += "---\n\n"

# Export document payload
with open("README.md", "w") as file:
    file.write(markdown_output)

print("\nAnalysis complete. Cleaned integers and descriptions applied to README.md.")